//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPOAPI.SsoReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EXPOAPI.SsoReference.SSOServiceSoap")]
    public interface SSOServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.AuthenticateUserResponse> AuthenticateUserAsync(EXPOAPI.SsoReference.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.ChangePasswordResponse> ChangePasswordAsync(EXPOAPI.SsoReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.GetUserInfoResponse> GetUserInfoAsync(EXPOAPI.SsoReference.GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.ForgotPasswordResponse> ForgotPasswordAsync(EXPOAPI.SsoReference.ForgotPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.UpdateUserPictureResponse> UpdateUserPictureAsync(EXPOAPI.SsoReference.UpdateUserPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.LoadUserPictureResponse> LoadUserPictureAsync(EXPOAPI.SsoReference.LoadUserPictureRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AppCredentials
    {
        
        private string appCodeField;
        
        private string appKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppCode
        {
            get
            {
                return this.appCodeField;
            }
            set
            {
                this.appCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppKey
        {
            get
            {
                return this.appKeyField;
            }
            set
            {
                this.appKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserPicture
    {
        
        private byte[] pictureUserField;
        
        private string pictureContentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] PictureUser
        {
            get
            {
                return this.pictureUserField;
            }
            set
            {
                this.pictureUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PictureContentType
        {
            get
            {
                return this.pictureContentTypeField;
            }
            set
            {
                this.pictureContentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo
    {
        
        private string nRPField;
        
        private string fullNameField;
        
        private string userEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NRP
        {
            get
            {
                return this.nRPField;
            }
            set
            {
                this.nRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserEmail
        {
            get
            {
                return this.userEmailField;
            }
            set
            {
                this.userEmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        public AuthenticateUserRequest()
        {
        }
        
        public AuthenticateUserRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, string Password)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthenticateUserResult;
        
        public AuthenticateUserResponse()
        {
        }
        
        public AuthenticateUserResponse(bool AuthenticateUserResult)
        {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NewPassword;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, string OldPassword, string NewPassword)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.OldPassword = OldPassword;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(bool ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public GetUserInfoRequest()
        {
        }
        
        public GetUserInfoRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EXPOAPI.SsoReference.UserInfo GetUserInfoResult;
        
        public GetUserInfoResponse()
        {
        }
        
        public GetUserInfoResponse(EXPOAPI.SsoReference.UserInfo GetUserInfoResult)
        {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForgotPasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public ForgotPasswordRequest()
        {
        }
        
        public ForgotPasswordRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForgotPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ForgotPasswordResult;
        
        public ForgotPasswordResponse()
        {
        }
        
        public ForgotPasswordResponse(string ForgotPasswordResult)
        {
            this.ForgotPasswordResult = ForgotPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PictureUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ContentType;
        
        public UpdateUserPictureRequest()
        {
        }
        
        public UpdateUserPictureRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, byte[] PictureUser, string ContentType)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.PictureUser = PictureUser;
            this.ContentType = ContentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateUserPictureResult;
        
        public UpdateUserPictureResponse()
        {
        }
        
        public UpdateUserPictureResponse(string UpdateUserPictureResult)
        {
            this.UpdateUserPictureResult = UpdateUserPictureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUserPictureRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public EXPOAPI.SsoReference.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public LoadUserPictureRequest()
        {
        }
        
        public LoadUserPictureRequest(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EXPOAPI.SsoReference.UserPicture LoadUserPictureResult;
        
        public LoadUserPictureResponse()
        {
        }
        
        public LoadUserPictureResponse(EXPOAPI.SsoReference.UserPicture LoadUserPictureResult)
        {
            this.LoadUserPictureResult = LoadUserPictureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SSOServiceSoapChannel : EXPOAPI.SsoReference.SSOServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SSOServiceSoapClient : System.ServiceModel.ClientBase<EXPOAPI.SsoReference.SSOServiceSoap>, EXPOAPI.SsoReference.SSOServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SSOServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.AuthenticateUserResponse> EXPOAPI.SsoReference.SSOServiceSoap.AuthenticateUserAsync(EXPOAPI.SsoReference.AuthenticateUserRequest request)
        {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.AuthenticateUserResponse> AuthenticateUserAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, string Password)
        {
            EXPOAPI.SsoReference.AuthenticateUserRequest inValue = new EXPOAPI.SsoReference.AuthenticateUserRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.Password = Password;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.ChangePasswordResponse> EXPOAPI.SsoReference.SSOServiceSoap.ChangePasswordAsync(EXPOAPI.SsoReference.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.ChangePasswordResponse> ChangePasswordAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, string OldPassword, string NewPassword)
        {
            EXPOAPI.SsoReference.ChangePasswordRequest inValue = new EXPOAPI.SsoReference.ChangePasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.OldPassword = OldPassword;
            inValue.NewPassword = NewPassword;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.GetUserInfoResponse> EXPOAPI.SsoReference.SSOServiceSoap.GetUserInfoAsync(EXPOAPI.SsoReference.GetUserInfoRequest request)
        {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.GetUserInfoResponse> GetUserInfoAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            EXPOAPI.SsoReference.GetUserInfoRequest inValue = new EXPOAPI.SsoReference.GetUserInfoRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).GetUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.ForgotPasswordResponse> EXPOAPI.SsoReference.SSOServiceSoap.ForgotPasswordAsync(EXPOAPI.SsoReference.ForgotPasswordRequest request)
        {
            return base.Channel.ForgotPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.ForgotPasswordResponse> ForgotPasswordAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            EXPOAPI.SsoReference.ForgotPasswordRequest inValue = new EXPOAPI.SsoReference.ForgotPasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).ForgotPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.UpdateUserPictureResponse> EXPOAPI.SsoReference.SSOServiceSoap.UpdateUserPictureAsync(EXPOAPI.SsoReference.UpdateUserPictureRequest request)
        {
            return base.Channel.UpdateUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.UpdateUserPictureResponse> UpdateUserPictureAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID, byte[] PictureUser, string ContentType)
        {
            EXPOAPI.SsoReference.UpdateUserPictureRequest inValue = new EXPOAPI.SsoReference.UpdateUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.PictureUser = PictureUser;
            inValue.ContentType = ContentType;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).UpdateUserPictureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXPOAPI.SsoReference.LoadUserPictureResponse> EXPOAPI.SsoReference.SSOServiceSoap.LoadUserPictureAsync(EXPOAPI.SsoReference.LoadUserPictureRequest request)
        {
            return base.Channel.LoadUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXPOAPI.SsoReference.LoadUserPictureResponse> LoadUserPictureAsync(EXPOAPI.SsoReference.AppCredentials AppCredentials, string UserID)
        {
            EXPOAPI.SsoReference.LoadUserPictureRequest inValue = new EXPOAPI.SsoReference.LoadUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((EXPOAPI.SsoReference.SSOServiceSoap)(this)).LoadUserPictureAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://db-sqldev01.saptaindra.co.id/SSO_TEST/SSOService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://db-sqldev01.saptaindra.co.id/SSO_TEST/SSOService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SSOServiceSoap,
            
            SSOServiceSoap12,
        }
    }
}
