name: Build and Deploy Backend to Azure API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore backend

      - name: Build
        run: dotnet build backend --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: expo-api
          publish-profile: ${{ secrets.AZUREAPPSERVICE_EXPO_API_PROFILE }}
          package: publish
